const CRYPTO_DATA = [
  {
    id: '1',
    name_id: 'ada',
    name: 'cardano',
    imageUrl: './assets/crypto-logos/ada-logo.png',
    scale: 0.85,
  },
  {
    id: '2',
    name_id: 'algo',
    name: 'algorand',
    imageUrl: './assets/crypto-logos/algo-logo.png',
    scale: 0.75,
  },
  {
    id: '3',
    name_id: 'lrc',
    name: 'loopring',
    imageUrl: './assets/crypto-logos/lrc-logo.png',
    scale: 1,
  },
  {
    id: '4',
    name_id: 'btc',
    name: 'bitcoin',
    imageUrl: './assets/crypto-logos/btc-logo.png',
    scale: 1,
  },
  {
    id: '5',
    name_id: 'doge',
    name: 'dogecoin',
    imageUrl: './assets/crypto-logos/doge-logo.png',
    scale: 1,
  },
  {
    id: '6',
    name_id: 'dot',
    name: 'polkadot',
    imageUrl: './assets/crypto-logos/dot-logo.png',
    scale: 0.9,
  },
  {
    id: '7',
    name_id: 'ltc',
    name: 'litecoin',
    imageUrl: './assets/crypto-logos/ltc-logo.png',
    scale: 1,
  },
  {
    id: '8',
    name_id: 'mkr',
    name: 'maker',
    imageUrl: './assets/crypto-logos/mkr-logo.png',
    scale: 1,
  },
  {
    id: '9',
    name_id: 'sol',
    name: 'solana',
    imageUrl: './assets/crypto-logos/sol-logo.png',
    scale: 0.9,
  },
  {
    id: '10',
    name_id: 'usdt',
    name: 'tether',
    imageUrl: './assets/crypto-logos/usdt-logo.png',
    scale: 0.9,
  },
  {
    id: '11',
    name_id: 'grt',
    name: 'the graph',
    imageUrl: './assets/crypto-logos/ship-logo.png',
    scale: 0.9,
  },
  {
    id: '12',
    name_id: 'eth',
    name: 'ethereum',
    imageUrl: './assets/crypto-logos/eth-logo.png',
    scale: 1,
  },
];

export default CRYPTO_DATA;
